### ISSUE TITLE
Error while adding package

### ISSUE THREAD

**Issue by fermuch** [jehartzog/galaxy-autoscale#1]
**Meteor version:** 1.6.0-beta.31
**System:** linux 64 bits.
**TL;DR:** seems like `request-progress` is missing in the NPM's depends.

```
 => Errors while adding packages:

While loading avariodev:galaxy-autoscale@1.0.0...:
error: Command failed: /home/fermuch/.meteor/packages/meteor-tool/.1.6.0-beta.31.nr39v5++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --update-binary
module.js:529
throw err;
^

Error: Cannot find module 'request-progress'
at Function.Module._resolveFilename (module.js:527:15)
at Function.Module._load (module.js:476:23)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/tmp/mt-1il0fdv.mkno/npm/node_modules1/.temp-1617jpq.25kxf/node_modules/phantomjs-prebuilt/install.js:9:23)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fermuch/.npm/_logs/2017-09-26T14_15_50_580Z-debug.log
module.js:529
throw err;
^

Error: Cannot find module 'request-progress'
at Function.Module._resolveFilename (module.js:527:15)
at Function.Module._load (module.js:476:23)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/tmp/mt-1il0fdv.mkno/npm/node_modules1/.temp-1617jpq.25kxf/node_modules/phantomjs-prebuilt/install.js:9:23)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fermuch/.npm/_logs/2017-09-26T14_15_50_580Z-debug.log


```

**Comment by jehartzog** [comment]
I initially had [a lot of issues](https://github.com/jehartzog/galaxy-autoscale/blob/master/package.js#L12) with the simple step of getting phantomjs and webdriverio installed via NPM and running inside the Meteor package.

After some troubleshooting it ran fine, including pushing a build to Galaxy and having it run there, but I'll need to look deeper into what the issue was to make sure it installs properly on a fresh install.

**Comment by fermuch** [comment]
That's weird, doing `meteor npm i -g phantomjs-prebuilt@2.1.15 webdriverio@4.8.0` does indeed work, but meteor add `jehartzog:galaxy-autoscale` doesn't.

**Comment by jehartzog** [comment]
Yup, that's sort of the behavior I was getting, I suspect it may be either:

1) I'm somehow importing them into the Meteor package system wrong, which I doubt since it seems [pretty simple](https://github.com/jehartzog/galaxy-autoscale/blob/master/package.js#L10).

2) There is some issue with how the Meteor package system installs npm dependencies that causes these packages to not be properly installed.

I'm going to try removing them from `Npm.depends` and adding them as peer dependencies of the package, which will require that extra step but at least it will work with a fresh install.

**Comment by jehartzog** [comment]
@fermuch Thanks for the report, I went ahead and just shifted to using phantomjs and webdriverio as peer dependencies with [v2.0.0](https://github.com/jehartzog/galaxy-autoscale/blob/master/CHANGELOG.md#200).

It's one extra command during the install process, but at least it will reliably work when people install and follow the quickstart steps.

**Comment by fermuch** [comment]
Thanks for the effort! I'll give it a try later!
